### ISSUE TITLE
Apply clippy suggestions

### ISSUE THREAD

**Issue by orhun** [eyeplum/cicero-tui#5]
When I run `cargo clippy`, I see a bunch of warnings/lints. Are you thinking of _fixing_ them soon? If so I can submit a PR for this.

P.S. It seems like a good opportunity to try out `cargo clippy --fix`

It would be also nice to have `clippy` checks in continuous integration workflow.

**Comment by eyeplum** [comment]
That sounds great! Please feel free to fix the clippy warnings and add it to the CI!
